version: '3.8'
services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=pass
            - POSTGRES_DB=user
        ports:
            - "5432:5432"
        volumes:
            - ./init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
    api_server:
        image: fastapi-app
        restart: always
        depends_on:
            - postgres
        logging:
            options:
                max-size: 10m
                max-file: "3"
        ports:
            - "3000:3000"
